### PR TITLE
new website

### PR DESCRIPTION
**Pull request by LeOptix**
this _should be_ the final PR (it has very few things **todo**, like adding the URLs for x84_64 and RPI downloads, but that can be directly commited to the amog-os repo after accepting this PR, so i personally see it as the final one for this new websus).

no comments to add, just take a look at it and give me your o(pi)nions 🧅 :] (well, give _us_, also Beau made a really nice job with this (and that 3rd acc is my personal acc which idk why is here (the fucking git installation messing stuff up again ig) but yeah))

> sus

### CODE REVIEW

**Comment by NoozAbooz** [comment]
looks great. will merge when we get toppat fully up and running

**Comment by formerlybased** [comment]
I am toppat

**Comment by ttaylor-st** [comment]
It's probably best to not depend on JavaScript for adding the navbar in :3

**Comment by therealolie** [comment]
:3

**Comment by formerlybased** [comment]
i commented here just to show my continued dedication to the AmogOS project and community

**Comment by LeOptix** [comment]
Closed in favor of #26

**Pull request closed without merging**
