### PR TITLE
[Read desc] Main Websus 2.0 Pull Request

### PR DESCRIPTION
**Pull request by LeOptix**
This is the `main` PR for the new websus for AmogOS
**Must note:**
- This _isn't_ the final version, I will keep to update the code until it's complete. (Even after that I
- some things like images, texts, credits, and more, should be written by someone else (as I'm not really up to date about things like whos the amogos team)
- files are ***very*** unorganised. i promise to fix that. i promise. *but not now :troll:*

### CODE REVIEW

**Comment by LeOptix** [comment]
accidentaly hit control enter while writing lmfao
what i was saying is that
(Even after completing the website, I will keep it up to date for changes and things that happen if wanted)

**Comment by formerlybased** [comment]
zamn

**Comment by BeauTheBeau** [comment]
when the sus

**Comment by LeOptix** [comment]
i forgor 💀 abt this

**Pull request closed without merging**
